// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-15s8eyTpw6KHUAqip2_-f00teCTFxhQ',
    appId: '1:399001084771:web:ef6853b8eb914a98a26956',
    messagingSenderId: '399001084771',
    projectId: 'travelmate-567b8',
    authDomain: 'travelmate-567b8.firebaseapp.com',
    storageBucket: 'travelmate-567b8.appspot.com',
    measurementId: 'G-NTFCP70FR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsVQqD7FbEy2La8VIdsVNx2RzR9j9zGcU',
    appId: '1:399001084771:android:3b95be2efbe3eb52a26956',
    messagingSenderId: '399001084771',
    projectId: 'travelmate-567b8',
    storageBucket: 'travelmate-567b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHSFIrYFkpqrqRXWu1zc-Q7T1tEqx4hI8',
    appId: '1:399001084771:ios:4a4a74c3c21bf289a26956',
    messagingSenderId: '399001084771',
    projectId: 'travelmate-567b8',
    storageBucket: 'travelmate-567b8.appspot.com',
    iosClientId: '399001084771-e6u1jr4qt3ga6pm1q13hl4ievolr3uo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHSFIrYFkpqrqRXWu1zc-Q7T1tEqx4hI8',
    appId: '1:399001084771:ios:4a4a74c3c21bf289a26956',
    messagingSenderId: '399001084771',
    projectId: 'travelmate-567b8',
    storageBucket: 'travelmate-567b8.appspot.com',
    iosClientId: '399001084771-e6u1jr4qt3ga6pm1q13hl4ievolr3uo5.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelapp',
  );
}
